# This is a basic workflow to help you get started with Actions

name: CI

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run a one-line script
        run: ls -la 
      - name: Install dependencies
        run: npm install
      # - name: Run npm CI
      #   run: npm ci
      - name: run unit test
        env:
          TOKENBOT: ${{ secrets.TOKENBOT }}
          CI: true
        run: npm test
      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.


      # every step must define a `uses` or `run` key
